// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsdBlA-FdDLUUGHcvu21IpPoaGHQ8KFU',
    appId: '1:210601199671:web:513aa4fae3842b7edfd7b2',
    messagingSenderId: '210601199671',
    projectId: 'moon-dark-e4bde',
    authDomain: 'moon-dark-e4bde.firebaseapp.com',
    databaseURL: 'https://moon-dark-e4bde-default-rtdb.firebaseio.com',
    storageBucket: 'moon-dark-e4bde.appspot.com',
    measurementId: 'G-R35MNP08LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSNnR0CON1ZPF0d3OSAtCi1VjBTUULDzw',
    appId: '1:210601199671:android:f09c540d870f8daedfd7b2',
    messagingSenderId: '210601199671',
    projectId: 'moon-dark-e4bde',
    databaseURL: 'https://moon-dark-e4bde-default-rtdb.firebaseio.com',
    storageBucket: 'moon-dark-e4bde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9SzV8bCWsIuDS1VtFbPG9Dgobz90qRw',
    appId: '1:210601199671:ios:dc67f145eddcf80cdfd7b2',
    messagingSenderId: '210601199671',
    projectId: 'moon-dark-e4bde',
    databaseURL: 'https://moon-dark-e4bde-default-rtdb.firebaseio.com',
    storageBucket: 'moon-dark-e4bde.appspot.com',
    iosClientId: '210601199671-m82fmsem55aseibhqg6hnssl82qogqhd.apps.googleusercontent.com',
    iosBundleId: 'com.sham.sham',
  );
}
